Repository NOW-SOPT-APP1-YeogiEottae/YeogiEottae-Android, pull requests merged in 2024-05, with the labels that each got.

#5 [add] #4 textAppearance추가
  app/src/main/res/values/text_appearance.xml
Labels: feat

#13 Feature/search list
  app/build.gradle
  app/src/main/java/com/sopt/yeogieottae/data/hotel/Hotel.kt
  app/src/main/java/com/sopt/yeogieottae/data/hotel/HotelViewModel.kt
  app/src/main/java/com/sopt/yeogieottae/ui/search/HotelListAdapter.kt
  app/src/main/java/com/sopt/yeogieottae/ui/search/SearchFragment.kt
  app/src/main/res/drawable/bg_hotelstar.xml
  app/src/main/res/drawable/bg_snackbar_hotel_favorite.xml
  app/src/main/res/drawable/ic_favorite_bg.xml
  app/src/main/res/drawable/ic_favorite_off.xml
  app/src/main/res/drawable/ic_favorite_on.xml
  app/src/main/res/drawable/ic_filter_except.xml
  app/src/main/res/drawable/ic_snackbar_line.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/drawable/img_searchlist_hotel.png
  app/src/main/res/drawable/img_searchlist_title.png
  app/src/main/res/layout/favorite_hotel_snackbar_layout.xml
  app/src/main/res/layout/favorite_room_snackbar_layout.xml
  app/src/main/res/layout/favorite_snackbar_off_layout.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_hotel_list.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/text_appearance.xml
  gradle/libs.versions.toml
Labels: design, feat

#19 Feature/hotel detail
  app/src/main/java/com/sopt/yeogieottae/data/model/Room.kt
  app/src/main/java/com/sopt/yeogieottae/ui/hotel/HotelFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/hotel/HotelRoomListAdapter.kt
  app/src/main/java/com/sopt/yeogieottae/ui/hotel/HotelRoomViewHolder.kt
  app/src/main/java/com/sopt/yeogieottae/ui/hotel/HotelViewModel.kt
  app/src/main/res/drawable/bg_radius_10_corner.xml
  app/src/main/res/drawable/bg_radius_20.xml
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_gift.xml
  app/src/main/res/drawable/ic_person.xml
  app/src/main/res/drawable/ic_price.xml
  app/src/main/res/drawable/img_toss.png
  app/src/main/res/layout/fragment_hotel.xml
  app/src/main/res/layout/item_hotel_room.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: design, feat

#27 Feature/hotel
  app/src/main/java/com/sopt/yeogieottae/network/ApiFactory.kt
  app/src/main/java/com/sopt/yeogieottae/network/HeaderInterceptor.kt
  app/src/main/java/com/sopt/yeogieottae/network/mapper/HotelMapper.kt
  app/src/main/java/com/sopt/yeogieottae/network/request/RequestLikeDto.kt
  app/src/main/java/com/sopt/yeogieottae/network/response/ResponseHotelDto.kt
  app/src/main/java/com/sopt/yeogieottae/network/response/ResponseLikeDto.kt
  app/src/main/java/com/sopt/yeogieottae/network/service/YeogieottaeService.kt
  app/src/main/java/com/sopt/yeogieottae/ui/hotel/HotelFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/hotel/HotelRoomListAdapter.kt
  app/src/main/java/com/sopt/yeogieottae/ui/hotel/HotelRoomViewHolder.kt
  app/src/main/java/com/sopt/yeogieottae/ui/hotel/HotelViewModel.kt
  app/src/main/java/com/sopt/yeogieottae/ui/like/FavoriteHotelViewModel.kt
  app/src/main/res/drawable/bg_date.xml
  app/src/main/res/drawable/img_hotel_0.png
  app/src/main/res/drawable/img_hotel_1.png
  app/src/main/res/drawable/img_hotel_2.png
  app/src/main/res/drawable/img_hotel_3.png
  app/src/main/res/drawable/img_hotel_4.png
  app/src/main/res/layout/fragment_hotel.xml
  app/src/main/res/layout/item_hotel_list.xml
  app/src/main/res/layout/item_hotel_room.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feat

#29 Feature/search api
  app/build.gradle
  app/src/main/java/com/sopt/yeogieottae/network/response/ResponseHotelDto.kt
  app/src/main/java/com/sopt/yeogieottae/network/response/ResponseLikeDto.kt
  app/src/main/java/com/sopt/yeogieottae/network/service/YeogieottaeService.kt
  app/src/main/java/com/sopt/yeogieottae/ui/search/SearchFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/search/SearchHotelListAdapter.kt
  app/src/main/java/com/sopt/yeogieottae/ui/search/SearchViewHolder.kt
  app/src/main/java/com/sopt/yeogieottae/ui/search/SearchViewModel.kt
  app/src/main/res/layout/favorite_room_snackbar_on_layout.xml
  app/src/main/res/layout/favorite_snackbar_off_layout.xml
  app/src/main/res/layout/favorite_snackbar_on_layout.xml
  app/src/main/res/layout/item_favorite_hotel.xml
  app/src/main/res/layout/item_hotel_list.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feat

#32 Feature/hotel-room-navi
  app/src/main/java/com/sopt/yeogieottae/MainActivity.kt
  app/src/main/java/com/sopt/yeogieottae/ui/hotel/HotelFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/hotel/HotelViewModel.kt
  app/src/main/java/com/sopt/yeogieottae/ui/room/RoomFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/room/RoomViewModel.kt
  app/src/main/java/com/sopt/yeogieottae/ui/search/SearchFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/search/SearchHotelListAdapter.kt
  app/src/main/java/com/sopt/yeogieottae/ui/search/SearchViewHolder.kt
  app/src/main/res/drawable/img_hotel_0.png
  app/src/main/res/drawable/img_hotel_1.png
  app/src/main/res/drawable/img_hotel_2.png
  app/src/main/res/drawable/img_hotel_3.png
  app/src/main/res/drawable/img_hotel_4.png
  app/src/main/res/layout/fragment_hotel.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat

#34 Feature/compare
  app/src/main/java/com/sopt/yeogieottae/data/Room.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/CompareFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/CompareViewModel.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/RoomAdapter.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/RoomDetailAdapter.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/RoomViewModel.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/empty/BottomSheetFragment.kt
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_person.xml
  app/src/main/res/drawable/ic_star_rate.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_compare.xml
  app/src/main/res/layout/fragment_like.xml
  app/src/main/res/layout/item_compare_detail.xml
  app/src/main/res/layout/item_compare_room.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: design

#24 Feature/bottomsheet-api
  app/src/main/java/com/sopt/yeogieottae/network/request/RequestRoomId.kt
  app/src/main/java/com/sopt/yeogieottae/network/response/ResponseCompareDto.kt
  app/src/main/java/com/sopt/yeogieottae/network/response/ResponseGetCompareDto.kt
  app/src/main/java/com/sopt/yeogieottae/network/service/YeogieottaeService.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/CompareFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/CompareNotEmptyFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/CompareViewModel.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/RoomAdapter.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/empty/BottomSheetFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/empty/BottomSheetViewModel.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/empty/LikeListAdapter.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/empty/LikeListViewHolder.kt
  app/src/main/res/layout/fragment_bottom_sheet.xml
  app/src/main/res/layout/fragment_compare_not_empty.xml
  app/src/main/res/layout/fragment_like.xml
  app/src/main/res/layout/item_compare_like_list.xml
Labels: feat

#33 Feature/compare-api
  app/src/main/java/com/sopt/yeogieottae/MainActivity.kt
  app/src/main/java/com/sopt/yeogieottae/network/request/RequestDeleteRoomId.kt
  app/src/main/java/com/sopt/yeogieottae/network/service/YeogieottaeService.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/BottomSheetFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/CompareEmptyFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/CompareFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/CompareNotEmptyFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/CompareViewModel.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/DeleteDialog.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/InnerAdapter.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/InnerViewHolder.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/LikeListAdapter.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/LikeListViewHolder.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/OuterAdapter.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/OuterViewHolder.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/RoomAdapter.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/RoomDetailAdapter.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/RoomViewModel.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/empty/BottomSheetViewModel.kt
  app/src/main/res/drawable/bg_white_radius_18dp.xml
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_expand_all.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/layout/dialog_delete.xml
  app/src/main/res/layout/fragment_compare_not_empty.xml
  app/src/main/res/layout/item_compare_detail.xml
  app/src/main/res/layout/item_compare_room.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  gradle/libs.versions.toml
  settings.gradle
Labels: design, feat

#36 Feature/refactor
  app/src/main/java/com/sopt/yeogieottae/MainActivity.kt
  app/src/main/java/com/sopt/yeogieottae/data/ResponseLikesDto.kt
  app/src/main/java/com/sopt/yeogieottae/data/Room.kt
  app/src/main/java/com/sopt/yeogieottae/data/model/Room.kt
  app/src/main/java/com/sopt/yeogieottae/network/mapper/HotelMapper.kt
  app/src/main/java/com/sopt/yeogieottae/network/response/ResponseHotelDto.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/CompareNotEmptyFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/CompareViewModel.kt
  app/src/main/java/com/sopt/yeogieottae/ui/compare/DeleteDialog.kt
  app/src/main/java/com/sopt/yeogieottae/ui/hotel/HotelFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/hotel/HotelRoomListAdapter.kt
  app/src/main/java/com/sopt/yeogieottae/ui/hotel/HotelRoomViewHolder.kt
  app/src/main/java/com/sopt/yeogieottae/ui/hotel/HotelViewModel.kt
  app/src/main/java/com/sopt/yeogieottae/ui/like/FavoriteHotelListAdapter.kt
  app/src/main/java/com/sopt/yeogieottae/ui/like/FavoriteHotelViewHolder.kt
  app/src/main/java/com/sopt/yeogieottae/ui/like/FavoriteHotelViewModel.kt
  app/src/main/java/com/sopt/yeogieottae/ui/like/LikeFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/room/RoomFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/room/RoomViewModel.kt
  app/src/main/java/com/sopt/yeogieottae/ui/search/SearchFragment.kt
  app/src/main/java/com/sopt/yeogieottae/ui/search/SearchHotelListAdapter.kt
  app/src/main/java/com/sopt/yeogieottae/ui/search/SearchViewHolder.kt
  app/src/main/java/com/sopt/yeogieottae/ui/search/SearchViewModel.kt
  app/src/main/res/drawable/img_toss.png
  app/src/main/res/drawable/img_tosspay.png
  app/src/main/res/layout/fragment_compare.xml
  app/src/main/res/layout/fragment_hotel.xml
  app/src/main/res/layout/item_compare_like_list.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat

#37 [Refactor] textview maxWidth 수정
  app/src/main/java/com/sopt/yeogieottae/ui/search/SearchViewModel.kt
  app/src/main/res/layout/fragment_hotel.xml
  app/src/main/res/layout/fragment_like.xml
  app/src/main/res/layout/item_favorite_hotel.xml
  app/src/main/res/layout/item_hotel_list.xml
Labels: feat

#42 Feature/search-layout-refactor
  app/src/main/res/drawable/bg_gray900_radius_4dp.xml
  app/src/main/res/drawable/ic_cancel.xml
  app/src/main/res/drawable/ic_expand_more.xml
  app/src/main/res/drawable/ic_filter.xml
  app/src/main/res/drawable/ic_sort.xml
  app/src/main/res/drawable/img_searchlist_title.png
  app/src/main/res/layout/fragment_search.xml
Labels: design
